### PR TITLE
Listen for a non-zero exit code from the go-search-replace process

### PR DESCRIPTION
**Pull request by markowsiak**
Listens for a non-zero exit code and throws loudly if one is received.

---
_This PR was started by: [git wf pr](https://github.com/groupon/git-workflow/releases/tag/v1.3.2)_

### CODE REVIEW

**Review by elazzabi — APPROVED** [review]
Looks good, but some tests are failing.

Does is it make sense to add another identifier to the exit function? ie instead of exiting with `1`, we exit with `invalid-file` (so we can display specific error messages in the future)

**Comment by markowsiak** [comment]
Thanks for taking a look @elazzabi. I'm missing an uncaught throw somewhere here and that's what's causing the test to fail.
I think if we wanted to handle different types of exits in the golang library we could.  I'm not sure if we can get more specific unless we do that.  We could check for different signals, like a SIGINT or other, but I'm not sure if we'll get huge value out of it as the process is spawned.

**Comment by elazzabi** [comment]
Ah @markowsiak yeah good call. Let's leave it as it is now 👍

**Review by jblz — APPROVED** [review]
lgtm

**Comment by elazzabi** [comment]
@markowsiak I see the bot has generated the appropriate changelog and tag, but it's still not showing in npm. Should we manually deploy it?

**Comment by markowsiak** [comment]
Yes I think we should.  I'm going to take a look at why that stopped working

**Pull request merged**
